import React from "react";
import { Sparkles, Camera } from "lucide-react";

interface ImageCreditProps {
  type: "ai" | "photo";
  credit: {
    source: string;
    name?: string;
    url?: string;
  };
  className?: string;
}

export default function ImageCredit({
  type,
  credit,
  className = "",
}: ImageCreditProps) {
  const Icon = type === "ai" ? Sparkles : Camera;

  return (
    <div
      className={`inline-flex items-center gap-2 rounded-full bg-black/20 backdrop-blur-sm 
                    px-3 py-1.5 text-xs text-white/90 transition-opacity hover:opacity-100 
                    ${className}`}
    >
      <Icon className="w-3 h-3" />

      {type === "ai" ? (
        <span>Generated by {credit.source}</span>
      ) : (
        <span>
          Photo by{" "}
          {credit.url ? (
            <a
              href={credit.url}
              target="_blank"
              rel="noopener noreferrer"
              className="hover:underline font-medium"
            >
              {credit.name}
            </a>
          ) : (
            <span className="font-medium">{credit.name}</span>
          )}
          {credit.source && (
            <>
              {" "}
              on <span className="font-medium">{credit.source}</span>
            </>
          )}
        </span>
      )}
    </div>
  );
}

// Example usage:
// <ImageCredit
//   type="ai"
//   credit={{ source: "Gemini Flash" }}
// />
//
// <ImageCredit
//   type="photo"
//   credit={{
//     source: "Unsplash",
//     name: "John Doe",
//     url: "https://unsplash.com/@johndoe"
//   }}
// />
